src_lib_svg_libegueb_svg_la_SOURCES += \
src/lib/svg/value/egueb_svg_value_animate_transform_type.c \
src/lib/svg/value/egueb_svg_value_animate_transform_type_private.h \
src/lib/svg/value/egueb_svg_value_clip_path.c \
src/lib/svg/value/egueb_svg_value_clip_path_private.h \
src/lib/svg/value/egueb_svg_value_color.c \
src/lib/svg/value/egueb_svg_value_color_private.h \
src/lib/svg/value/egueb_svg_value_display.c \
src/lib/svg/value/egueb_svg_value_display_private.h \
src/lib/svg/value/egueb_svg_value_fill_rule.c \
src/lib/svg/value/egueb_svg_value_fill_rule_private.h \
src/lib/svg/value/egueb_svg_value_length_list.c \
src/lib/svg/value/egueb_svg_value_length_list_private.h \
src/lib/svg/value/egueb_svg_value_matrix.c \
src/lib/svg/value/egueb_svg_value_matrix_private.h \
src/lib/svg/value/egueb_svg_value_number.c \
src/lib/svg/value/egueb_svg_value_number_private.h \
src/lib/svg/value/egueb_svg_value_overflow.c \
src/lib/svg/value/egueb_svg_value_overflow_private.h \
src/lib/svg/value/egueb_svg_value_paint.c \
src/lib/svg/value/egueb_svg_value_paint_private.h \
src/lib/svg/value/egueb_svg_value_point.c \
src/lib/svg/value/egueb_svg_value_point_private.h \
src/lib/svg/value/egueb_svg_value_rect.c \
src/lib/svg/value/egueb_svg_value_rect_private.h \
src/lib/svg/value/egueb_svg_value_spread_method.c \
src/lib/svg/value/egueb_svg_value_spread_method_private.h \
src/lib/svg/value/egueb_svg_value_stroke_dasharray.c \
src/lib/svg/value/egueb_svg_value_stroke_dasharray_private.h \
src/lib/svg/value/egueb_svg_value_stroke_line_cap.c \
src/lib/svg/value/egueb_svg_value_stroke_line_cap_private.h \
src/lib/svg/value/egueb_svg_value_stroke_line_join.c \
src/lib/svg/value/egueb_svg_value_stroke_line_join_private.h \
src/lib/svg/value/egueb_svg_value_text_anchor.c \
src/lib/svg/value/egueb_svg_value_text_anchor_private.h \
src/lib/svg/value/egueb_svg_value_visibility.c \
src/lib/svg/value/egueb_svg_value_visibility_private.h \
src/lib/svg/value/egueb_svg_value_zoom_and_pan.c \
src/lib/svg/value/egueb_svg_value_zoom_and_pan_private.h
