GENERATED_FILES += \
src/lib/svg/elements/esvg_generated_element.c \
src/lib/svg/elements/esvg_generated_element_a.c \
src/lib/svg/elements/esvg_generated_element_animate.c \
src/lib/svg/elements/esvg_generated_element_animate_transform.c \
src/lib/svg/elements/esvg_generated_element_animation.c \
src/lib/svg/elements/esvg_generated_element_circle.c \
src/lib/svg/elements/esvg_generated_element_clip_path.c \
src/lib/svg/elements/esvg_generated_element_defs.c \
src/lib/svg/elements/esvg_generated_element_element_rect.c \
src/lib/svg/elements/esvg_generated_element_ellipse.c \
src/lib/svg/elements/esvg_generated_element_g.c \
src/lib/svg/elements/esvg_generated_element_gradient.c \
src/lib/svg/elements/esvg_generated_element_image.c \
src/lib/svg/elements/esvg_generated_element_polygon.c \
src/lib/svg/elements/esvg_generated_element_polyline.c \
src/lib/svg/elements/esvg_generated_element_line.c \
src/lib/svg/elements/esvg_generated_element_linear_gradient.c \
src/lib/svg/elements/esvg_generated_element_path.c \
src/lib/svg/elements/esvg_generated_element_rect.c \
src/lib/svg/elements/esvg_generated_element_radial_gradient.c \
src/lib/svg/elements/esvg_generated_element_script.c \
src/lib/svg/elements/esvg_generated_element_set.c \
src/lib/svg/elements/esvg_generated_element_stop.c \
src/lib/svg/elements/esvg_generated_element_style.c \
src/lib/svg/elements/esvg_generated_element_svg.c \
src/lib/svg/elements/esvg_generated_element_text.c \
src/lib/svg/elements/esvg_generated_element_use.c \
src/lib/svg/elements/esvg_generated_element_video.c

dist_installed_svgheaders_DATA += \
src/lib/svg/elements/esvg_element.h \
src/lib/svg/elements/esvg_element_a.h \
src/lib/svg/elements/esvg_element_a_private.h \
src/lib/svg/elements/esvg_element_animate.h \
src/lib/svg/elements/esvg_element_animate_transform.h \
src/lib/svg/elements/esvg_element_animation.h \
src/lib/svg/elements/esvg_element_circle.h \
src/lib/svg/elements/esvg_element_clip_path.h \
src/lib/svg/elements/esvg_element_defs.h \
src/lib/svg/elements/esvg_element_ellipse.h \
src/lib/svg/elements/esvg_element_g.h \
src/lib/svg/elements/esvg_element_gradient.h \
src/lib/svg/elements/esvg_element_image.h \
src/lib/svg/elements/esvg_element_line.h \
src/lib/svg/elements/esvg_element_linear_gradient.h \
src/lib/svg/elements/esvg_element_path.h \
src/lib/svg/elements/esvg_element_polygon.h \
src/lib/svg/elements/esvg_element_polyline.h \
src/lib/svg/elements/esvg_element_radial_gradient.h \
src/lib/svg/elements/esvg_element_rect.h \
src/lib/svg/elements/esvg_element_script.h \
src/lib/svg/elements/esvg_element_set.h \
src/lib/svg/elements/esvg_element_stop.h \
src/lib/svg/elements/esvg_element_style.h \
src/lib/svg/elements/esvg_element_svg.h \
src/lib/svg/elements/esvg_element_text.h \
src/lib/svg/elements/esvg_element_use.h \
src/lib/svg/elements/esvg_element_video.h

src_lib_svg_libesvg_la_SOURCES += \
src/lib/svg/elements/esvg_element.c \
src/lib/svg/elements/esvg_element_private.h \
src/lib/svg/elements/esvg_element_a.c \
src/lib/svg/elements/esvg_element_animate.c \
src/lib/svg/elements/esvg_element_animate_private.h \
src/lib/svg/elements/esvg_element_animate_transform.c \
src/lib/svg/elements/esvg_element_animate_transform_private.h \
src/lib/svg/elements/esvg_element_animation.c \
src/lib/svg/elements/esvg_element_animation_private.h \
src/lib/svg/elements/esvg_element_circle.c \
src/lib/svg/elements/esvg_element_clip_path.c \
src/lib/svg/elements/esvg_element_clip_path_private.h \
src/lib/svg/elements/esvg_element_defs.c \
src/lib/svg/elements/esvg_element_ellipse.c \
src/lib/svg/elements/esvg_element_g.c \
src/lib/svg/elements/esvg_element_gradient.c \
src/lib/svg/elements/esvg_element_gradient_private.h \
src/lib/svg/elements/esvg_element_image.c \
src/lib/svg/elements/esvg_element_line.c \
src/lib/svg/elements/esvg_element_linear_gradient.c \
src/lib/svg/elements/esvg_element_path.c \
src/lib/svg/elements/esvg_element_polygon.c \
src/lib/svg/elements/esvg_element_polyline.c \
src/lib/svg/elements/esvg_element_radial_gradient.c \
src/lib/svg/elements/esvg_element_rect.c \
src/lib/svg/elements/esvg_element_script.c \
src/lib/svg/elements/esvg_element_set.c \
src/lib/svg/elements/esvg_element_stop.c \
src/lib/svg/elements/esvg_element_style.c \
src/lib/svg/elements/esvg_element_svg.c \
src/lib/svg/elements/esvg_element_text.c \
src/lib/svg/elements/esvg_element_use.c \
src/lib/svg/elements/esvg_element_video.c \
src/lib/svg/elements/esvg_element_a.h \
src/lib/svg/elements/esvg_element_animate.h \
src/lib/svg/elements/esvg_element_animate_transform.h \
src/lib/svg/elements/esvg_element_animation.h \
src/lib/svg/elements/esvg_element_circle.h \
src/lib/svg/elements/esvg_element_clip_path.h \
src/lib/svg/elements/esvg_element_defs.h \
src/lib/svg/elements/esvg_element_ellipse.h \
src/lib/svg/elements/esvg_element_g.h \
src/lib/svg/elements/esvg_element_gradient.h \
src/lib/svg/elements/esvg_element.h \
src/lib/svg/elements/esvg_element_image.h \
src/lib/svg/elements/esvg_element_linear_gradient.h \
src/lib/svg/elements/esvg_element_line.h \
src/lib/svg/elements/esvg_element_path.h \
src/lib/svg/elements/esvg_element_polygon.h \
src/lib/svg/elements/esvg_element_polyline.h \
src/lib/svg/elements/esvg_element_radial_gradient.h \
src/lib/svg/elements/esvg_element_rect.h \
src/lib/svg/elements/esvg_element_script.h \
src/lib/svg/elements/esvg_element_set.h \
src/lib/svg/elements/esvg_element_stop.h \
src/lib/svg/elements/esvg_element_stop_private.h \
src/lib/svg/elements/esvg_element_style.h \
src/lib/svg/elements/esvg_element_style_private.h \
src/lib/svg/elements/esvg_element_svg.h \
src/lib/svg/elements/esvg_element_svg_private.h \
src/lib/svg/elements/esvg_element_text.h \
src/lib/svg/elements/esvg_element_use.h \
src/lib/svg/elements/esvg_element_video.h \
src/lib/svg/elements/esvg_element_video_private.h
